// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfjicylpgpbnozcxkvmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmamljeWxwZ3Bibm96Y3hrdm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzA0ODUsImV4cCI6MjA2ODQwNjQ4NX0.7DZK9LN0QzAELgUYFPQhXtR8vjvqLie0GdEe8VuSkQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});